CREATE DATABASE '/var/lib/firebird/2.5/data/T.FDB'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1251;

CREATE TABLE T (
    F  INTEGER
);


CREATE TABLE ATSPU(
RE	DOUBLE PRECISION,
TXT	VARCHAR(32),
C4	CHAR(1)
);

CREATE TABLE BL(
B BLOB
);

COMMIT;

INSERT INTO ATSPU VALUES(3.141592,'PREVED','T');
INSERT INTO ATSPU VALUES(2.718281828459045,'MEDVED','F');

COMMIT;